//
//  HomeViewController.swift
//  temp
//
//  Created by Ivan Stajcer on 11.02.2022..
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import UIKit
import Themer

final class HomeViewController: UIViewController {
    // MARK: - Properties
    private let mainView = HomeView()
    
    // MARK: - Lifecycle
    override func loadView() {
        super.loadView()
        view = mainView
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        navigationItem.title =  "Home"
    }
}

// MARK: - Public methods
extension HomeViewController {
}

// MARK: - Private methods
private extension HomeViewController {
    
}

